project_id = "mqzuvqwsaeguphqjwvap"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.get-drive-files]
verify_jwt = false

[functions.download-project-document]
verify_jwt = false

[functions.upload-project-documents]
verify_jwt = false

[functions.google-drive-integration]
verify_jwt = false

[functions.send-mandante-notification]
verify_jwt = false

[functions.send-contractor-notification]
verify_jwt = false

[functions.gmail-token-manager]
verify_jwt = false

[functions.google-drive-token-manager]
verify_jwt = false

[functions.upload-documents-to-drive]
verify_jwt = false

[functions.payment-status-automation]
verify_jwt = false

[functions.verify-email-access]
verify_jwt = false

[functions.verify-email-user-access]
verify_jwt = false

[functions.get-payment-detail-public]
verify_jwt = false

[functions.update-payment-detail-public]
verify_jwt = false

[functions.ensure-unique-access-url]
verify_jwt = false

[functions.regenerate-access-urls]
verify_jwt = false

[functions.verify-mandante-user-email]
verify_jwt = false

[functions.update-payment-status-mandante]
verify_jwt = false

[functions.send-cc-copy]
verify_jwt = false

[functions.set-email-access]
verify_jwt = false

[functions.upload-project-photos]
verify_jwt = false

[functions.record-payment-approval]
verify_jwt = false

[functions.send-adicional-notification]
verify_jwt = false

[functions.send-adicional-response]
verify_jwt = false

[functions.send-rfi-notification]
verify_jwt = false

[functions.send-rfi-response]
verify_jwt = false

[functions.rfi-message]
verify_jwt = false

[functions.send-rfi-message-notification]
verify_jwt = false

[functions.send-rfi-close-notification]
verify_jwt = false

[functions.get-drive-folder-files]
verify_jwt = false
